[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/find-schemes"
  to = "/.netlify/functions/find-schemes"
  status = 200

[context.production.environment]
  PYTHON_VERSION = "3.9"
